### ISSUE TITLE
diesel的数据操作是否会阻塞actix线程?

### ISSUE THREAD

**Issue by kran** [Kilerd/rubble#51]
看actix文档的话, 里面说diesel还不支持异步操作, 建议使用actor, 但rubble里面没有使用这样的结构, 请问是有什么技巧吗?(actor确实比较麻烦)

**Comment by Kilerd** [comment]
是的，并没有使用 `actor.send()` 的方式。`send` 会把操作转移到一组独立的线程进行处理，然后在通知 handler 的线程，但是 rubble 其实并不存在任何比较耗时的 SQL 查询，因此没有采用 actor 的处理方式。

**Comment by kran** [comment]
👍 明白了
